spring:
  application:
    name: BigXmlReader

bigxmlreader:
  csv-reader:
    skip-header: false
    column-separator: ';'
  xml-reader:
    namespace-aware: true
    chunk-size: 30
    root-node-local-name: Document
    body-node-local-name: PayInf
    body-node-namespace-uri: http://www.equens.com/zvs/archive/transaction
  xml-chunk-writer:
    target-folder: ${CHUNKS_OUTPUT_FOLDER:C:/Users/maxzu/Documents/cpl/zadanko_od_piotra/output}
    target-file-prefix: chunked_payments_
