spring:
  application:
    name: BigXmlReader

bigxmlreader:
  csv-reader:
    skip-header: false
    column-separator: ';'
  xml-reader:
    namespace-aware: false
    remove-namespace-manually-enabled: true
    namespaces-comma-separated: ar,bb3.1.2,mx8.1.8
