spring:
  application:
    name: BigXmlReader

bigxmlreader:
  csv-reader:
    skip-header: false
    column-separator: ';'
  xml-reader:
    namespace-aware: true
    body-node-local-name: PayInf
    body-node-namespace-uri: http://www.equens.com/zvs/archive/transaction
